// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Item struct {
	ID            int    `json:"id"`
	DeskripsiItem string `json:"deskripsiItem"`
	HargaBeli     string `json:"hargaBeli"`
	Stok          int    `json:"stok"`
}

type Mutation struct {
}

type NewItem struct {
	DeskripsiItem string `json:"deskripsiItem"`
	HargaBeli     string `json:"hargaBeli"`
	Stok          int    `json:"stok"`
}

type Query struct {
}

type UpdateItem struct {
	ID            int    `json:"id"`
	DeskripsiItem string `json:"deskripsiItem"`
	HargaBeli     string `json:"hargaBeli"`
	Stok          int    `json:"stok"`
}
